export { default as CMM } from './CMM.jsx';
export { default as StationBedCMM } from './StationBedCMM.jsx';
export { default as RapidPrototyping } from './RapidPrototyping.jsx';
export { default as CNCMachinesHURCO } from './CNCMachinesHURCO.jsx';
export { default as LaserWeldingMachines } from './LaserWeldingMachines.jsx';
export { default as LaserCuttingMachines } from './LaserCuttingMachines.jsx';
export { default as LabEquipmentsSinowon } from './LabEquipmentsSinowon.jsx';
export { default as TestMeasureEquipments } from './TestMeasureEquipments.jsx';
export { default as LaserCleaningMachines } from './LaserCleaningMachines.jsx';
export { default as LaserEngravingMachines } from './LaserEngravingMachines.jsx';
export { default as PortableCmmAccessories } from './PortableCmmAccessories.jsx';
export { default as FERO3DMeasurementTechnology } from './FERO3DMeasurementTechnology.jsx';
// export { default as ImgLogo2 } from './logo/logo-sm.png';
// export { default as ImgLogoHeader2 } from './logo/logo-white.png';